# Kubernetes Secret for Revolucare Backend Service
# 
# IMPORTANT: This file contains placeholders for secret values. In a real deployment:
# 1. Never store actual secrets in version control
# 2. Use a secure method to create the Secret (e.g., kubectl create secret or a secrets management solution)
# 3. Consider using Sealed Secrets, HashiCorp Vault, or cloud provider secret management services
#
# Usage:
# This Secret provides sensitive configuration for the Revolucare backend service, including:
# - Database credentials
# - Redis cache credentials
# - Authentication secrets
# - API keys for external services
# - Security and encryption keys
#
# Secret Rotation:
# Implement regular rotation of these secrets based on security policies
# Database credentials: Every 90 days
# API keys: Every 60 days
# Authentication secrets: Every 30 days
#
# Access Control:
# This Secret should only be accessible by the backend service and authorized administrators

apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
  namespace: revolucare
  labels:
    app: revolucare
    component: backend
    part-of: revolucare-platform
    managed-by: kubernetes
  annotations:
    kubernetes.io/description: "Sensitive configuration for Revolucare backend service"
type: Opaque
data:
  # Database credentials
  DATABASE_PASSWORD: YmFzZTY0X2VuY29kZWRfZGF0YWJhc2VfcGFzc3dvcmQ=
  DATABASE_CONNECTION_STRING: YmFzZTY0X2VuY29kZWRfZGF0YWJhc2VfY29ubmVjdGlvbl9zdHJpbmc=
  
  # Redis cache credentials
  REDIS_PASSWORD: YmFzZTY0X2VuY29kZWRfcmVkaXNfcGFzc3dvcmQ=
  REDIS_CONNECTION_STRING: YmFzZTY0X2VuY29kZWRfcmVkaXNfY29ubmVjdGlvbl9zdHJpbmc=
  
  # Authentication secrets
  JWT_SECRET: YmFzZTY0X2VuY29kZWRfand0X3NlY3JldA==
  JWT_REFRESH_SECRET: YmFzZTY0X2VuY29kZWRfand0X3JlZnJlc2hfc2VjcmV0
  COOKIE_SECRET: YmFzZTY0X2VuY29kZWRfY29va2llX3NlY3JldA==
  
  # AI service credentials
  OPENAI_API_KEY: YmFzZTY0X2VuY29kZWRfb3BlbmFpX2FwaV9rZXk=
  OPENAI_ORGANIZATION_ID: YmFzZTY0X2VuY29kZWRfb3BlbmFpX29yZ2FuaXphdGlvbl9pZA==
  AZURE_FORM_RECOGNIZER_KEY: YmFzZTY0X2VuY29kZWRfYXp1cmVfZm9ybV9yZWNvZ25pemVyX2tleQ==
  
  # Communication service credentials
  SENDGRID_API_KEY: YmFzZTY0X2VuY29kZWRfc2VuZGdyaWRfYXBpX2tleQ==
  TWILIO_ACCOUNT_SID: YmFzZTY0X2VuY29kZWRfdHdpbGlvX2FjY291bnRfc2lk
  TWILIO_AUTH_TOKEN: YmFzZTY0X2VuY29kZWRfdHdpbGlvX2F1dGhfdG9rZW4=
  
  # Payment processing credentials
  STRIPE_SECRET_KEY: YmFzZTY0X2VuY29kZWRfc3RyaXBlX3NlY3JldF9rZXk=
  STRIPE_WEBHOOK_SECRET: YmFzZTY0X2VuY29kZWRfc3RyaXBlX3dlYmhvb2tfc2VjcmV0
  
  # Calendar integration credentials
  GOOGLE_CALENDAR_CLIENT_SECRET: YmFzZTY0X2VuY29kZWRfZ29vZ2xlX2NhbGVuZGFyX2NsaWVudF9zZWNyZXQ=
  MICROSOFT_GRAPH_CLIENT_SECRET: YmFzZTY0X2VuY29kZWRfbWljcm9zb2Z0X2dyYXBoX2NsaWVudF9zZWNyZXQ=
  
  # Storage credentials
  STORAGE_ACCOUNT_NAME: YmFzZTY0X2VuY29kZWRfc3RvcmFnZV9hY2NvdW50X25hbWU=
  STORAGE_ACCOUNT_KEY: YmFzZTY0X2VuY29kZWRfc3RvcmFnZV9hY2NvdW50X2tleQ==
  STORAGE_CONNECTION_STRING: YmFzZTY0X2VuY29kZWRfc3RvcmFnZV9jb25uZWN0aW9uX3N0cmluZw==
  
  # Security keys
  ENCRYPTION_KEY: YmFzZTY0X2VuY29kZWRfZW5jcnlwdGlvbl9rZXk=
  
  # Monitoring credentials
  SENTRY_DSN: YmFzZTY0X2VuY29kZWRfc2VudHJ5X2Rzbg==