apiVersion: v1
kind: Secret
metadata:
  name: web-secrets
  namespace: revolucare
  labels:
    app: revolucare
    component: web
    part-of: revolucare-platform
    managed-by: kubernetes
  annotations:
    kubernetes.io/description: "Sensitive configuration for Revolucare web frontend service"
type: Opaque
data:
  # Authentication secrets
  NEXTAUTH_SECRET: "YmFzZTY0X2VuY29kZWRfbmV4dGF1dGhfc2VjcmV0"
  NEXTAUTH_URL: "YmFzZTY0X2VuY29kZWRfbmV4dGF1dGhfdXJs"
  API_SECRET_KEY: "YmFzZTY0X2VuY29kZWRfYXBpX3NlY3JldF9rZXk="
  COOKIE_SECRET: "YmFzZTY0X2VuY29kZWRfY29va2llX3NlY3JldA=="
  
  # OAuth credentials
  GOOGLE_CLIENT_ID: "YmFzZTY0X2VuY29kZWRfZ29vZ2xlX2NsaWVudF9pZA=="
  GOOGLE_CLIENT_SECRET: "YmFzZTY0X2VuY29kZWRfZ29vZ2xlX2NsaWVudF9zZWNyZXQ="
  MICROSOFT_CLIENT_ID: "YmFzZTY0X2VuY29kZWRfbWljcm9zb2Z0X2NsaWVudF9pZA=="
  MICROSOFT_CLIENT_SECRET: "YmFzZTY0X2VuY29kZWRfbWljcm9zb2Z0X2NsaWVudF9zZWNyZXQ="
  MICROSOFT_TENANT_ID: "YmFzZTY0X2VuY29kZWRfbWljcm9zb2Z0X3RlbmFudF9pZA=="
  
  # External service APIs
  GOOGLE_MAPS_API_KEY: "YmFzZTY0X2VuY29kZWRfZ29vZ2xlX21hcHNfYXBpX2tleQ=="
  STRIPE_PUBLISHABLE_KEY: "YmFzZTY0X2VuY29kZWRfc3RyaXBlX3B1Ymxpc2hhYmxlX2tleQ=="
  
  # Monitoring and observability
  SENTRY_DSN: "YmFzZTY0X2VuY29kZWRfc2VudHJ5X2Rzbg=="
  ANALYTICS_ID: "YmFzZTY0X2VuY29kZWRfYW5hbHl0aWNzX2lk"
  
  # Security keys
  ENCRYPTION_KEY: "YmFzZTY0X2VuY29kZWRfZW5jcnlwdGlvbl9rZXk="