apiVersion: v1
kind: ConfigMap
metadata:
  name: web-config
  namespace: revolucare
  labels:
    app: revolucare
    component: web
    part-of: revolucare-platform
    managed-by: kubernetes
  annotations:
    kubernetes.io/description: "Non-sensitive configuration for Revolucare web frontend service"
data:
  # Application Settings
  NODE_ENV: "production"
  NEXT_PUBLIC_API_URL: "https://api.revolucare.com"
  NEXT_PUBLIC_APP_URL: "https://revolucare.com"
  NEXT_PUBLIC_APP_NAME: "Revolucare"
  NEXT_PUBLIC_APP_DESCRIPTION: "Next-generation care management platform"
  NEXT_PUBLIC_APP_VERSION: "1.0.0"
  NEXT_PUBLIC_SUPPORT_EMAIL: "support@revolucare.com"
  NEXT_PUBLIC_SUPPORT_PHONE: "+1-555-123-4567"
  NEXT_TELEMETRY_DISABLED: "1"
  
  # Localization Settings
  NEXT_PUBLIC_DEFAULT_LOCALE: "en"
  NEXT_PUBLIC_AVAILABLE_LOCALES: "en,es"
  
  # Feature Flags
  NEXT_PUBLIC_ANALYTICS_ENABLED: "true"
  NEXT_PUBLIC_FEATURE_CARE_PLAN_GENERATOR: "true"
  NEXT_PUBLIC_FEATURE_PROVIDER_MATCHING: "true"
  NEXT_PUBLIC_FEATURE_REAL_TIME_AVAILABILITY: "true"
  NEXT_PUBLIC_FEATURE_DOCUMENT_ANALYSIS: "true"
  NEXT_PUBLIC_FEATURE_ANALYTICS_DASHBOARD: "true"
  NEXT_PUBLIC_CALENDAR_INTEGRATION_ENABLED: "true"
  NEXT_PUBLIC_GOOGLE_CALENDAR_ENABLED: "true"
  NEXT_PUBLIC_MICROSOFT_CALENDAR_ENABLED: "true"
  
  # Document Settings
  NEXT_PUBLIC_MAX_UPLOAD_SIZE_MB: "25"
  NEXT_PUBLIC_ALLOWED_FILE_TYPES: "pdf,doc,docx,jpg,jpeg,png"
  
  # Theme Configuration
  NEXT_PUBLIC_THEME_COLOR: "#4F46E5"
  NEXT_PUBLIC_SECONDARY_COLOR: "#EC4899"
  NEXT_PUBLIC_ACCENT_COLOR: "#8B5CF6"
  NEXT_PUBLIC_ERROR_COLOR: "#EF4444"
  NEXT_PUBLIC_SUCCESS_COLOR: "#10B981"
  NEXT_PUBLIC_WARNING_COLOR: "#F59E0B"
  NEXT_PUBLIC_INFO_COLOR: "#3B82F6"
  NEXT_PUBLIC_BACKGROUND_COLOR: "#FFFFFF"
  NEXT_PUBLIC_TEXT_COLOR: "#1F2937"
  NEXT_PUBLIC_FONT_FAMILY: "Inter, system-ui, sans-serif"
  NEXT_PUBLIC_ENABLE_DARK_MODE: "true"
  NEXT_PUBLIC_DEFAULT_THEME: "light"
  
  # User Experience Settings
  NEXT_PUBLIC_ENABLE_ANIMATIONS: "true"
  NEXT_PUBLIC_REDUCED_MOTION_PREFERENCE: "false"
  NEXT_PUBLIC_ENABLE_NOTIFICATIONS: "true"
  NEXT_PUBLIC_NOTIFICATION_POLLING_INTERVAL: "30000"
  NEXT_PUBLIC_SESSION_TIMEOUT_MINUTES: "30"
  NEXT_PUBLIC_IDLE_TIMEOUT_MINUTES: "15"
  NEXT_PUBLIC_ENABLE_HELP_WIDGET: "true"
  NEXT_PUBLIC_ENABLE_FEEDBACK_WIDGET: "true"
  NEXT_PUBLIC_ENABLE_ACCESSIBILITY_TOOLS: "true"
  
  # Data Display Settings
  NEXT_PUBLIC_PAGINATION_DEFAULT_LIMIT: "10"
  NEXT_PUBLIC_PAGINATION_MAX_LIMIT: "100"
  NEXT_PUBLIC_SEARCH_MIN_CHARS: "3"
  NEXT_PUBLIC_DEBOUNCE_DELAY: "300"
  
  # Feature-Specific Settings
  NEXT_PUBLIC_PROVIDER_SEARCH_RADIUS_DEFAULT: "10"
  NEXT_PUBLIC_PROVIDER_SEARCH_RADIUS_MAX: "50"
  NEXT_PUBLIC_PROVIDER_SEARCH_RADIUS_UNIT: "miles"
  NEXT_PUBLIC_CARE_PLAN_MAX_OPTIONS: "3"
  NEXT_PUBLIC_CARE_PLAN_MIN_CONFIDENCE: "70"
  
  # Maintenance Settings
  NEXT_PUBLIC_MAINTENANCE_MODE: "false"
  NEXT_PUBLIC_MAINTENANCE_MESSAGE: "Revolucare is currently undergoing scheduled maintenance. Please check back soon."