# Kubernetes manifest for cert-manager configuration
# cert-manager version: 1.11.0
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
  labels:
    app: revolucare
    part-of: revolucare-platform
    managed-by: kubernetes
  annotations:
    kubernetes.io/description: "Production Let's Encrypt certificate issuer for Revolucare platform"
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: security@revolucare.com
    privateKeySecretRef:
      name: letsencrypt-prod-account-key
    solvers:
      # HTTP-01 challenge solver
      - http01:
          ingress:
            class: nginx
      # DNS-01 challenge solver for wildcard certificates
      - dns01:
          route53:
            region: us-east-1
            hostedZoneID: ${HOSTED_ZONE_ID}
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
  labels:
    app: revolucare
    part-of: revolucare-platform
    managed-by: kubernetes
  annotations:
    kubernetes.io/description: "Staging Let's Encrypt certificate issuer for testing certificate issuance"
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: security@revolucare.com
    privateKeySecretRef:
      name: letsencrypt-staging-account-key
    solvers:
      # HTTP-01 challenge solver
      - http01:
          ingress:
            class: nginx
      # DNS-01 challenge solver for wildcard certificates
      - dns01:
          route53:
            region: us-east-1
            hostedZoneID: ${HOSTED_ZONE_ID}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: revolucare-wildcard-cert
  namespace: revolucare
  labels:
    app: revolucare
    part-of: revolucare-platform
    managed-by: kubernetes
  annotations:
    kubernetes.io/description: "Wildcard certificate for Revolucare domains"
spec:
  secretName: revolucare-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: revolucare.com
  dnsNames:
    - revolucare.com
    - "*.revolucare.com"
  duration: 2160h # 90 days
  renewBefore: 360h # 15 days before expiration
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  usages:
    - digital signature
    - key encipherment
    - server auth
    - client auth