apiVersion: v1
kind: Service
metadata:
  name: revolucare-backend
  namespace: revolucare
  labels:
    app: revolucare
    component: backend
    part-of: revolucare-platform
    managed-by: kubernetes
  annotations:
    kubernetes.io/description: "Revolucare backend API service"
    prometheus.io/scrape: "true"
    prometheus.io/port: "3000"
    prometheus.io/path: "/api/metrics"
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 80
    targetPort: http
    protocol: TCP
  - name: websocket
    port: 8080
    targetPort: websocket
    protocol: TCP
  selector:
    app: revolucare
    component: backend
  sessionAffinity: None
  publishNotReadyAddresses: false