apiVersion: v1
kind: Service
metadata:
  name: revolucare-web
  namespace: revolucare
  labels:
    app: revolucare
    component: web
    part-of: revolucare-platform
    managed-by: kubernetes
  annotations:
    kubernetes.io/description: "Revolucare web frontend service"
    prometheus.io/scrape: "true"
    prometheus.io/port: "80"
    prometheus.io/path: "/metrics"
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
  selector:
    app: revolucare
    component: web
  sessionAffinity: None
  publishNotReadyAddresses: false